//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTNEXT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bai_viet
    {
        public int BaiVietID { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> DanhMucID { get; set; }
        public string Hinh_Anh { get; set; }
        public Nullable<System.DateTime> Thoi_Gian_Tao { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Danh_Muc Danh_Muc { get; set; }
        public virtual User User { get; set; }
    }
}
